### ISSUE TITLE
mount failed: Operation not permitted

### ISSUE THREAD

**Issue by hasamba** [google/hashr#61]
trying to hash several windows iso's, getting mount failed every time, even when running as SUDO
`docker run -it --network hashr_net -v /opt/hashr/windows_iso:/data/windows us-docker.pkg.dev/osdfir-registry/hashr/release/hashr -storage postgres -postgres_host hashr_postgresql -postgres_port 5432 -postgres_user XXX -postgres_password XXX -postgres_db hashr -importers windows -windows_iso_repo_path /data/windows -exporters postgres`

error: 
`Stderr: mount: /tmp/hashr-server2022.iso-3119761407/mnt: mount failed: Operation not permitted.`

thanks

**Comment by jkppr** [comment]
Thanks for raising this issue. 

hashr is trying to directly mount the ISO file within the Docker container. iirc, Docker doesn't allow this by default for security reasons. 

For an easy workaround, use the `--privileged` flag with your `docker run` command.

I'll create a follow-up issue to explore alternatives to using `mount` e.g. by extracting the iso content instead.

**Comment by jkppr** [comment]
I tested your command with the `--privileged` flag and a Windows ISO file and can confirm it is working.
